/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        body:    ["'Inter'", "sans-serif"],
        mono:    ["'JetBrains Mono'", "monospace"],
      },
      colors: {
        bg:        "#0B0F1A",
        surface:   "#111827",
        card:      "#161D2E",
        "card-2":  "#1C2539",
        border:    "#1E2D45",
        "border-2":"#243352",
        blue:      "#3B82F6",
        "blue-dim":"#1D4ED8",
        cyan:      "#22D3EE",
        text:      "#F0F4FF",
        muted:     "#8B9BB8",
        dim:       "#4A5568",
      },
      animation: {
        "loader-line": "loaderLine 2.4s cubic-bezier(0.16,1,0.3,1) forwards",
        "fade-up":     "fadeUp 0.9s cubic-bezier(0.16,1,0.3,1) both",
        "fade-in":     "fadeIn 0.6s ease both",
        "slide-up":    "slideUp 1s cubic-bezier(0.16,1,0.3,1) both",
        "slide-left":  "slideLeft 0.9s cubic-bezier(0.16,1,0.3,1) both",
        "slide-right": "slideRight 0.9s cubic-bezier(0.16,1,0.3,1) both",
        marquee:       "marquee 30s linear infinite",
        float:         "float 6s ease-in-out infinite",
        pulse2:        "pulse2 3s ease-in-out infinite",
        "border-spin": "borderSpin 4s linear infinite",
        shimmer:       "shimmer 2s ease-in-out infinite",
      },
      keyframes: {
        loaderLine:  { "0%": { width: "0%" }, "100%": { width: "100%" } },
        fadeUp:      { "0%": { opacity: "0", transform: "translateY(32px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        fadeIn:      { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp:     { "0%": { opacity: "0", transform: "translateY(60px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        slideLeft:   { "0%": { opacity: "0", transform: "translateX(-40px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        slideRight:  { "0%": { opacity: "0", transform: "translateX(40px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        marquee:     { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
        float:       { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-12px)" } },
        pulse2:      { "0%,100%": { opacity: "0.4", transform: "scale(1)" }, "50%": { opacity: "1", transform: "scale(1.05)" } },
        borderSpin:  { "0%": { "--angle": "0deg" }, "100%": { "--angle": "360deg" } },
        shimmer:     { "0%,100%": { opacity: "0.5" }, "50%": { opacity: "1" } },
      },
    },
  },
  plugins: [],
};
