export const personal = {
  name: "Kareem Saeed",
  role: "Full Stack Developer",
  tagline: "Building scalable systems — from database to pixel.",
  bio: "Full Stack Developer with 1+ year of production experience. I build clean, performant, and maintainable applications across the entire stack — .NET Core APIs, React & Angular frontends, Clean Architecture. Currently at ITI deepening my full-stack expertise.",
  email: "kareemsaeed258@gmail.com",
  phone: "+201278594745",
  location: "Cairo, Egypt",
  github: "https://github.com/karemsaeed20020",
  linkedin: "https://www.linkedin.com/in/kareem-saed/",
  avatar: "/images/WhatsApp Image 2026-05-09 at 12.28.13.jpeg",
  cv: "/cv.pdf",
  quote: "I don't just ship features — I cut API calls by 40% and ship 2 weeks early.",
  available: true,
};

export const stats = [
  { num: "1+",   label: "Years in Production" },
  { num: "−40%", label: "API Calls Reduced" },
  { num: "+20%", label: "Checkout Uplift" },
  { num: "4+",   label: "Full Stack Apps" },
];

export const techBadges = [
  ".NET Core", "ASP.NET", "C#", "EF Core", "CQRS", "MediatR", "Entity Framework", "LINQ", "MVC",
  "Redis", "SignalR", "SQL Server", "React", "Next.js", "Angular",
  "TypeScript", "Redux", "Tailwind", "Docker", "Azure", "Clean Architecture",
];

export const skills = [
  { category: "Backend", color: "#C8813A", items: [
    { name: "C# / .NET Core", pct: 90 },
    { name: "ASP.NET Web API", pct: 88 },
    { name: "Entity Framework Core", pct: 85 },
    { name: "CQRS · MediatR", pct: 80 },
    { name: "Redis · SignalR", pct: 75 },
    { name: "SQL Server", pct: 85 },
{ name: "MVC", pct: 90 },
{ name: "linq", pct: 95 },
  ]},
  { category: "Frontend", color: "#6B8F71", items: [
    { name: "React / Next.js", pct: 92 },
    { name: "Angular", pct: 78 },
    { name: "TypeScript", pct: 86 },
    { name: "Redux / React Query", pct: 88 },
    { name: "Tailwind CSS", pct: 90 },
{ name: "Bootstrap", pct: 90 },
{ name: "HTML & CSS", pct: 95 },
{ name: "Javascript", pct: 90 },
  ]},
  { category: "DevOps & Tools", color: "#B85C38", items: [
    { name: "Git / GitHub", pct: 90 },
    { name: "Docker", pct: 70 },
    { name: "Azure", pct: 65 },
    { name: "CI/CD / GitHub Actions", pct: 70 },
  ]},
];

export const concepts = [
  "Clean Architecture", "SOLID Principles", "Design Patterns", "CQRS",
  "Onion Architecture", "Repository + Unit of Work", "Specification Pattern",
  "JWT Authentication", "Unit Testing", "Data Structures", "Algorithms",
  "REST APIs", "Agile / Scrum", "Error Handling & Logging",
];

export const projects = [
  {
    id: 1,
    title: "Clinic Management System",
    subtitle: "Healthcare · REST API · Real-time",
    year: "2026",
    desc: "Scalable REST API with Clean Architecture and CQRS via MediatR. Redis distributed caching, SignalR for real-time doctor notifications and live clinic queues, rate limiting against brute-force, and Hangfire for automated token cleanups.",
    tags: ["ASP.NET Core", "Redis", "CQRS", "SignalR", "Hangfire", "JWT"],
    image: "/images/project-clinic.jpg",
    github: "https://github.com/karemsaeed20020/HotelBooking",
    live: "#",
    accent: "#C8813A",
    featured: true,
  },
  {
    id: 2,
    title: "Entry E-Commerce Platform",
    subtitle: "Multi-vendor · 3 Roles · Real-time Search",
    year: "2026",
    desc: "Multi-vendor marketplace with 3 user roles (Customer, Seller, Admin), JWT auth, smart filtering, persistent cart & wishlist, product comparison, seller dashboard with full inventory CRUD, order tracking, and real-time earnings analytics.",
    tags: ["Next.js", "React", "MongoDB", "Express", "Redux", "JWT"],
    image: "/images/preview.png",
    github: "https://github.com/karemsaeed20020/Entry-Ecommerce",
    live: "https://drive.google.com/file/d/1AAW2CVSCUi58q8D3smifFIJqbg8aJ7fT/view",
    accent: "#6B8F71",
    featured: true,
  },
{
  id: 3,
  title: "Social App Platform",
  subtitle: "Social Media · Real-time · i18n · RTL",
  year: "2025",
  desc: "Full-featured social media platform with infinite scrolling feed, post CRUD (text/image + privacy levels), comments with nested replies, like/bookmark/share, real-time notifications, dark/light theme, and full English/Arabic i18n with RTL layout.",
  tags: ["Next.js", "React", "TypeScript", "Tailwind", "React Query", "Zustand", "Next-intl", "shadcn/ui"],
  image: "/images/Screenshot 2026-05-09 130042.png",
  github: "https://github.com/karemsaeed20020/social-app-next",
  live: "https://social-app-next-liard.vercel.app/",
  accent: "#4A90D9",
  featured: true,
  features: [
    "🔐 JWT Authentication — Login, Signup, Logout, Change Password, Route Protection",
    "📰 News Feed — Infinite scrolling, paginated posts, privacy filters (Public/Following/Only Me)",
    "✏️ Post CRUD — Create, edit, delete posts with text/images, emoji picker, image lightbox",
    "❤️ Social Actions — Like, bookmark, share/repost posts with custom comments",
    "💬 Comments — Add, edit, delete comments, nested replies, like comments",
    "👤 Profiles — View own/others profiles, update avatar & cover photo, profile tabs",
    "👥 Social Features — Follow/unfollow, suggested friends, debounced user search",
    "🔔 Real-time Notifications — Unread badge, notification list, mark as read, supports likes/comments/follows/shares",
    "🌍 Internationalization — English & Arabic with RTL layout, locale-based routing (/en/, /ar/)",
    "🎨 Theme Support — Dark/Light mode with next-themes, persisted preference",
    "📱 Responsive UI — Mobile-first, 3-column desktop grid, skeleton loaders, toast notifications, glassmorphism navbar"
  ],
},  {
    id: 4,
    title: "Hotel Booking Application",
    subtitle: "Enterprise · Payments · Clean Arch",
    year: "2025",
    desc: "Enterprise hotel booking with role-based access, room management, bookings, payments, cancellations, and refunds. Clean Architecture, CQRS, Repository & Unit of Work, Specification & Result patterns, JWT + refresh tokens.",
    tags: ["ASP.NET Core", "EF Core", "SQL Server", "CQRS", "JWT"],
    image: "/images/project-hotel.jpg",
    github: "https://github.com/karemsaeed20020/HotelBooking",
    live: "#",
    accent: "#B85C38",
    featured: true,
  },
  {
    id: 5,
    title: "Bookify",
    subtitle: "Book Rental · .NET 9 · PDF Reports",
    year: "2025",
    desc: "Full-featured book rental system using .NET 9.0, Clean Architecture, generic repository & Unit of Work, Data Protection, AutoMapper, and automated PDF report generation.",
    tags: [".NET 9", "MVC", "EF Core", "Bootstrap", "jQuery"],
    image: "/images/project-bookify.jpg",
    github: "https://github.com/karemsaeed20020/Bookify",
    live: "#",
    accent: "#9B9490",
    featured: false,
  },
  {
    id: 6,
    title: "Airbnb Clone",
    subtitle: "Full Stack · SignalR · Angular",
    year: "2025",
    desc: "Airbnb-inspired platform with Clean Architecture, real-time notifications via SignalR, Angular + Tailwind frontend, complete property listing and booking flows, and user review system.",
    tags: ["Angular", "ASP.NET Core", "SignalR", "Tailwind", "EF Core"],
    image: "/images/project-airbnb.jpg",
    github: "https://github.com/abdallah2799/iti-airbnb-clone",
    live: "#",
    accent: "#C8813A",
    featured: false,
  },
  {
    id: 7,
    title: "Attendance System",
    subtitle: "Desktop · WinForms · EF Core",
    year: "2025",
    desc: "Desktop attendance management built with WinForms, C#, EF Core and SQL Server. Employee management, attendance records, shift tracking, and report generation.",
    tags: ["C#", "WinForms", "EF Core", "SQL Server"],
    image: "/images/project-attendance.jpg",
    github: "https://github.com/Mahmoud10Gamal/Attendance",
    live: "#",
    accent: "#6B8F71",
    featured: false,
  },
{
  id: 8,
  title: "Super Fitness",
  subtitle: "Fitness & Nutrition · Multi-language · Protected Routes",
  year: "2025",
  desc: "Personalized fitness and nutrition guidance platform with exercise browsing by muscle group, class schedules, healthy meal details, and user profiles. Full authentication flow with guest/protected routes and multi-language support.",
  tags: ["React", "TypeScript", "Vite", "Tailwind", "React Query", "Zustand", "i18next", "React Hook Form", "Zod"],
  image: "/images/Screenshot 2026-05-09 130501.png",
  github: "https://github.com/karemsaeed20020/Super-Fitness",
  live: "https://super-fitness-three.vercel.app/",
  accent: "#22C55E",
  featured: true,
  highlights: [
    "Exercise browsing by muscle group via dynamic routes",
    "Multi-language support (i18next) with locale-aware API headers",
    "Global state with Zustand + context providers",
    "API data fetching & caching with React Query",
    "Reusable forms with React Hook Form + Zod validation",
    "Theme support + toast notifications",
    "Guest route & protected route access control",
  ],
},
{
  id: 9,
  title: "Chat Application",
  subtitle: "Real-time Messaging · Private & Group Chats · SignalR",
  desc: "Full-featured real-time chat application with private and group conversations, media sharing, message read receipts, typing indicators, and user presence. Built with ASP.NET Core 10 backend and React frontend.",
  tags: ["ASP.NET Core", "SignalR", "SQL Server", "EF Core", "JWT", "Hangfire", "FluentValidation"],
  image: "/images/project-chat.jpg",
  github: "https://github.com/karemsaeed20020/Chat-Application",
  live: "#",
  accent: "#8B5CF6",
  featured: false,
  highlights: [
    "Real-time messaging with SignalR WebSockets",
    "Private & group chats with message pinning",
    "Media sharing (images/videos/files) atomic with messages",
    "Read receipts (double-check) + typing indicators",
    "JWT auth with ASP.NET Core Identity",
    "Hangfire background jobs for emails",
    "FluentValidation + centralized exception handling",
    "Audit logging for user actions",
  ],
},
  {
  id: 10,
  title: "Quran Application",
  subtitle: "Real-time Messaging · Private & Group Chats · SignalR",
  desc: "Full-featured real-time chat application with private and group conversations, media sharing, message read receipts, typing indicators, and user presence. Built with ASP.NET Core 10 backend and React frontend.",
  tags: ["ASP.NET Core", "SignalR", "SQL Server", "EF Core", "JWT", "Hangfire", "FluentValidation"],
  image: "/images/Screenshot 2026-05-12 011620.png",
  github: "https://github.com/karemsaeed20020/Quran",
  live: "https://quran-flax-chi.vercel.app/",
  accent: "#8B5CF6",
  featured: true
},

];

export const experience = [
  {
    role: "Frontend Developer",
    company: "Apps Square",
    period: "Jun 2024 – Jun 2025",
    type: "Full-time",
    location: "Cairo, Egypt",
    color: "#C8813A",
    points: [
      "Built **'Outlet'** e-commerce for Saudi pharmacies — React + Shadcn UI + Redux + React Query",
      "Reduced API calls by **40%**, cut backend dependency by **50%**, shipped **2 weeks early**",
      "Increased checkout completion by **20%** via optimized React Query mutation patterns",
      "Integrated REST APIs independently by studying documentation end-to-end",
    ],
  },
  {
    role: "Full Stack .NET & Angular Intern",
    company: "Information Technology Institute (ITI)",
    period: "Jul 2025 – Dec 2025",
    type: "Internship",
    location: "Tanta, Egypt",
    color: "#6B8F71",
    points: [
      "Developed and deployed **4+ full-stack** applications using .NET Core and Angular",
      "Built Airbnb clone with **Clean Architecture**, SignalR, Angular, and Tailwind CSS",
      "Collaborated in **Agile sprints**, improving team delivery speed and communication",
      "Improved team productivity by **25%** through reusable component architecture",
    ],
  },
];

export const education = {
  degree: "B.Sc. Computer & Information Science",
  university: "Tanta University",
  faculty: "Faculty of Computer and Information",
  period: "Sep 2020 – Jun 2024",
  gpa: "3.6 / 4.0  (B+)",
  project: "ArchReality — Graduation Project",
  projectGrade: "A+",
};
